# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.2-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: clone submodules
          command: |
            git submodule update --init --recursive

      - run:
          name: install git-lfs
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install

      - run:
          name: pull lfs storage
          command: |
            git lfs pull

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements_prerequisites.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install prerequisites
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements_prerequisites.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements_prerequisites.txt" }}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements_prerequisites.txt
            pip3 install -r requirements.txt
            pip3 install -r requirements_dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: unit tests
          command: |
            . venv/bin/activate
            python3 -m unittest rr_extract_test.py reader_test.py

      - store_artifacts:
          path: test-reports
          destination: test-reports